import * as fs from 'node:fs/promises';
import { describe, it, expect, vi, afterEach } from 'vitest';

vi.mock('node:fs/promises', () => ({
  readFile: vi.fn(),
}));

import { parseCookiesForDomain } from '../../services/cookies-parser';

const NETSCAPE_HEADER = '# Netscape HTTP Cookie File\n# Generated by yt-dlp.\n\n';

function makeCookieLine(domain: string, name: string, value: string, expiry = '9999999999'): string {
  const subdomainFlag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
  return `${domain}\t${subdomainFlag}\t/\tTRUE\t${expiry}\t${name}\t${value}`;
}

afterEach(() => {
  vi.restoreAllMocks();
});

describe('parseCookiesForDomain', () => {
  it('returns cookies matching an exact subdomain wildcard', async () => {
    const content =
      NETSCAPE_HEADER +
      [
        makeCookieLine('.tiktok.com', 'tt_chain_token', 'abc123'),
        makeCookieLine('.tiktok.com', 'sessionid', 'sess456'),
        makeCookieLine('.youtube.com', 'CONSENT', 'ignored'),
      ].join('\n');
    vi.mocked(fs.readFile).mockResolvedValueOnce(content as never);

    const result = await parseCookiesForDomain('/fake/cookies.txt', 'v19-webapp.tiktok.com');

    expect(result).toBe('tt_chain_token=abc123; sessionid=sess456');
  });

  it('matches exact domain (no leading dot)', async () => {
    const content = NETSCAPE_HEADER + makeCookieLine('www.tiktok.com', 'msToken', 'tok789') + '\n';
    vi.mocked(fs.readFile).mockResolvedValueOnce(content as never);

    const result = await parseCookiesForDomain('/fake/cookies.txt', 'www.tiktok.com');

    expect(result).toBe('msToken=tok789');
  });

  it('returns empty string when no cookies match the domain', async () => {
    const content = NETSCAPE_HEADER + makeCookieLine('.youtube.com', 'CONSENT', 'val') + '\n';
    vi.mocked(fs.readFile).mockResolvedValueOnce(content as never);

    const result = await parseCookiesForDomain('/fake/cookies.txt', 'v19-webapp.tiktok.com');

    expect(result).toBe('');
  });

  it('returns empty string when the file cannot be read', async () => {
    vi.mocked(fs.readFile).mockRejectedValueOnce(new Error('ENOENT'));

    const result = await parseCookiesForDomain('/nonexistent/cookies.txt', 'tiktok.com');

    expect(result).toBe('');
  });

  it('skips comment lines and blank lines', async () => {
    const content = '# comment\n\n' + makeCookieLine('.tiktok.com', 'ttwid', 'w1') + '\n';
    vi.mocked(fs.readFile).mockResolvedValueOnce(content as never);

    const result = await parseCookiesForDomain('/fake/cookies.txt', 'tiktok.com');

    expect(result).toBe('ttwid=w1');
  });

  it('skips malformed lines with fewer than 7 fields', async () => {
    const content = '.tiktok.com\tTRUE\t/\n' + makeCookieLine('.tiktok.com', 'sid_tt', 's1') + '\n';
    vi.mocked(fs.readFile).mockResolvedValueOnce(content as never);

    const result = await parseCookiesForDomain('/fake/cookies.txt', 'tiktok.com');

    expect(result).toBe('sid_tt=s1');
  });

  it('does not match a domain that only shares a suffix (anti-spoofing)', async () => {
    const content = NETSCAPE_HEADER + makeCookieLine('.tiktok.com', 'secret', 'val') + '\n';
    vi.mocked(fs.readFile).mockResolvedValueOnce(content as never);

    // eviltiktok.com must NOT match .tiktok.com
    const result = await parseCookiesForDomain('/fake/cookies.txt', 'eviltiktok.com');

    expect(result).toBe('');
  });
});
